epsilon_anneal_time: 100000
# use the Q_Learner to train
agent_output_type: "q"
learner: "comax_q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

central_loss: 1
qmix_loss: 1

td_lambda: 0.6
lr: 0.0005

central_mixing_embed_dim: 128
central_action_embed: 1
central_mac: "basic_central_mac"
central_agent: "central_rnn"
central_rnn_hidden_dim: 64
central_mixer: "ff"
atten_head: 4

w: 0.8

name: "comax"